ARG RUBY_VERSION=3.1.6
FROM ruby:${RUBY_VERSION}-slim-bookworm AS base

ENV TZ=America/New_York

WORKDIR /app

ARG NODE_VERSION=21
ARG YARN_VERSION=1.22.22
ARG BUNDLER_VERSION=2.5.22
ENV RUBY_BASE_IMAGE=${RUBY_VERSION}-node-${NODE_VERSION}

RUN apt-get update && \
    apt-get upgrade -y --no-install-recommends && \
    apt-get autoremove -y && \
    apt --fix-broken install -y && \
    apt-get install -y --no-install-recommends curl wget unzip && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean
# Add Node.js repository & Yarn Repositories
RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - && \
    mkdir -p /etc/apt/keyrings && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /etc/apt/keyrings/yarn.gpg && \
    echo 'deb [signed-by=/etc/apt/keyrings/yarn.gpg] http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list
# Install Node.js, Yarn, and build tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    nodejs yarn=${YARN_VERSION}-1 \
    git make pkg-config libxslt-dev libxml2-dev \
    libpq-dev libghc-zlib-dev zlib1g-dev chromium && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean

COPY bin/vaultshell /bin

# Configure bundler
ENV LANG=C.UTF-8 \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3


# Remove unused default gems (adjust the Ruby version directory if needed)
RUN rm -rf /usr/local/lib/ruby/gems/3.1.0/specifications/default
