version: 2.1


jobs:
  trivy-check:
    parameters:
      ruby_version:
        type: string
      node_version:
        type: string
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:$CI_UTILS_IMAGE_TAG
    environment:
      REGISTRY_URL: library/ruby
      DOCKER_REGISTRY: 'harbor.k8s.libraries.psu.edu'
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: "trivy"
        command: |
          export BUILD_ARGS="--build-arg RUBY_VERSION=<< parameters.ruby_version >> --build-arg NODE_MAJOR=<< parameters.node_version >>"
          export REGISTRY_IMAGE=$REGISTRY_URL-<< parameters.ruby_version >>-node-<< parameters.node_version >>
          export IMAGE_TAG="$(date +%Y%m%d),latest"
          /usr/local/bin/trivy-check

  build-and-push:
    parameters:
      ruby_version:
        type: string
      node_version:
        type: string
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:$CI_UTILS_IMAGE_TAG
    environment:
      REGISTRY_URL: library/ruby
      DOCKER_REGISTRY: 'harbor.k8s.libraries.psu.edu'
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: "build and push"
        command: |
          export BUILD_ARGS="--build-arg RUBY_VERSION=<< parameters.ruby_version >> --build-arg NODE_MAJOR=<< parameters.node_version >>"
          export REGISTRY_IMAGE=$REGISTRY_URL-<< parameters.ruby_version >>-node-<< parameters.node_version >>
          export IMAGE_TAG="$(date +%Y%m%d),latest"
          /usr/local/bin/build-and-push

workflows:
  trivy_check:
    triggers:
      - schedule:
          cron: '15 4 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - trivy-check:
          context: org-global
          matrix:
            parameters:
              node_version: ['12', '14', '15', '16']
              ruby_version: ['2.6.5', '2.6.6', '2.6.7', '2.7.1', '2.7.2', '2.7.3', '2.7.5', '3.0.1']
          filters:
            branches:
              only:
                - master

  build_and_push:
    jobs:
      - build-and-push:
          context: org-global
          matrix:
            parameters:
              node_version: ['12', '14', '15', '16']
              ruby_version: ['2.6.5', '2.6.6', '2.6.7', '2.7.1', '2.7.4', '2.7.2', '2.7.3', '2.7.4','2.7.5', '3.0.1']
          filters:
            branches:
              only:
                - master
