version: 2.1


jobs:
  create-db:
    docker:
      - image: ghcr.io/oras-project/oras:v0.13.0
    environment:
      REGISTRY_URL: library/ruby
    steps:
    - setup_remote_docker
    - run:
        name: "Download Trivy DB"
        command: |
          mkdir trivy-db
          oras pull ghcr.io/aquasecurity/trivy-db:2 -a
          tar -xvf db.tar.gz -C trivy-db
    - persist_to_workspace:
        root: trivy-db
        paths:
          - "."
  trivy-check:
    parameters:
      ruby_version:
        type: string
      node_version:
        type: string
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:v3.0.1
    environment:
      REGISTRY_URL: library/ruby
      TRIVY_CACHE_DIR: trivy-db
      DOCKER_REGISTRY: 'harbor.k8s.libraries.psu.edu'
    steps:
    - setup_remote_docker
    - checkout
    - attach_workspace:
        at: trivy-db
    - run:
        name: "trivy"
        command: |
          export BUILD_ARGS="--build-arg RUBY_VERSION=<< parameters.ruby_version >> --build-arg NODE_MAJOR=<< parameters.node_version >>"
          export REGISTRY_IMAGE=$REGISTRY_URL-<< parameters.ruby_version >>-node-<< parameters.node_version >>
          export IMAGE_TAG="$(date +%Y%m%d),latest"
          /usr/local/bin/trivy-check

  build-and-push:
    parameters:
      ruby_version:
        type: string
      node_version:
        type: string
    docker:
      - image: harbor.k8s.libraries.psu.edu/library/ci-utils:$CI_UTILS_IMAGE_TAG
    environment:
      REGISTRY_URL: library/ruby
      DOCKER_REGISTRY: 'harbor.k8s.libraries.psu.edu'
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: "build and push"
        command: |
          export BUILD_ARGS="--build-arg RUBY_VERSION=<< parameters.ruby_version >> --build-arg NODE_MAJOR=<< parameters.node_version >>"
          export REGISTRY_IMAGE=$REGISTRY_URL-<< parameters.ruby_version >>-node-<< parameters.node_version >>
          export IMAGE_TAG="$(date +%Y%m%d),latest"
          /usr/local/bin/build-and-push

workflows:
  trivy_check:
    triggers:
      - schedule:
          cron: '15 4 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - create-db:
        context: org-global
      - trivy-check:
          context: org-global
          matrix:
            parameters:
              node_version: ['12', '14', '15', '16']
              ruby_version: ['2.6.5', '2.7.1', '2.7.3', '2.7.5', '2.7.6', '3.1.2']
          filters:
            branches:
              only:
                - master

  build_and_push:
    jobs:
      - build-and-push:
          context: org-global
          matrix:
            parameters:
              node_version: ['12', '15', '16']
              ruby_version: ['2.6.5', '2.7.1', '2.7.3', '2.7.5', '2.7.6', '3.1.2']
          filters:
            branches:
              only:
                - master
