version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    parameters:
      ruby_version:
        type: string
      node_version:
        type: string
    executor: docker/docker
    environment:
      REGISTRY_URL: library/ruby
      DOCKER_LOGIN: 'robot$circleci'
    steps:
    - setup_remote_docker
    - checkout
    - docker/check:
        registry: harbor.k8s.libraries.psu.edu
    - docker/build:
        image: $REGISTRY_URL-<< parameters.ruby_version >>-node-<< parameters.node_version >>
        registry: harbor.k8s.libraries.psu.edu
        extra_build_args: "--build-arg RUBY_VERSION=<< parameters.ruby_version >>"
        tag: $(date +%Y%m%d)
    - docker/push:
        registry: harbor.k8s.libraries.psu.edu
        image: $REGISTRY_URL-<< parameters.ruby_version >>-node-<< parameters.node_version >>
        tag: $(date +%Y%m%d)

workflows:
  docker_push:
    triggers:
      - schedule:
          cron: '5 19 * * 2'
    jobs:
      - build-and-push:
          matrix:
            parameters:
              node_version: ['10', '12']
              ruby_version: ['2.6.6', '2.7.1', '2.7.2']
          filters:
            branches:
              only:
                - master
