name: Publish

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [10, 12]
        ruby: [2.6.3, 2.6.4, 2.6.5, 2.6.0]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
        NODE_MAJOR: ${{ matrix.node }}
      with:
        name: psul/ruby
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        # registry: docker.pkg.github.com
        tags: "${{ matrix.ruby }}-node-${{ matrix.node }}"
        buildargs: RUBY_VERSION,NODE_MAJOR
