name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [10, 11]
        ruby: [2.6.3]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v1
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} docker.pkg.github.com
    - name: Build
      run: docker buildx build --build-arg RUBY_VERSION=${{ matrix.ruby_version }} -t docker.pkg.github.com/psu-libraries/ruby-base:${{ matrix.ruby_version }} .
