name: Publish

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # node: [10, 12]
        ruby: [2.6.3]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: crazy-max/ghaction-docker-buildx@v1
    - name: Build and Push
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} docker.pkg.github.com
        docker buildx build \
          --push \
          --build-arg RUBY_VERSION=${{ matrix.ruby }} \
          -t docker.pkg.github.com/psu-libraries/ruby-base/ruby:${{ matrix.ruby }} .