name: Publish

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # node: [10, 12]
        ruby: [2.6.3]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: elgohr/Publish-Docker-Github-Action@master
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
      with:
        name: ruby-base/ruby
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: docker.pkg.github.com
        tags: "${{ matrix.ruby }}"
        buildargs: RUBY_VERSION